apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: dgraph
  name: dgraph
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dgraph
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: dgraph
    spec:
      containers:
      - image: dgraph/dgraph:v20.03.0
        name: dgraph
        resources: {}
status: {}
